### ISSUE TITLE
ToDo: finish the inventory, and reset weight-limit

### ISSUE THREAD

**Issue by langbakk** [StudioErrilhl/HSS#57]
Currently the weightlimit is set to 1000 - should be reduced, and a more fine-tuned weight-setting should be set up, with different weights for each item.

Also make it possible to get rid of items in the inventory.

**Comment by langbakk** [comment]
Weight-limit is currently set to 75, and set weight (for adding items) is set to 2. I will need to look into how I can manage getting the weight set per item, based on either the dict item_weights, or other information.

**Comment by StudioErrilhl** [comment]
Currently moved to 0.27

**Comment by StudioErrilhl** [comment]
Decided to ditch the weight-limit for HSS - you can basically keep whatever you pick up in the inventory, without thinking about weight.
