### ISSUE TITLE
ToDo: make the overslept variable / reason better

### ISSUE THREAD

**Issue by langbakk** [StudioErrilhl/HSS#6]
Fix the "overslept" thing - create reasons that makes it understandable that you overslept (maybe also have an exhaustion stat, that builds up over time if there is a lot of crap happening)

**Comment by langbakk** [comment]
Also, enable the player to purchase an alarm clock, or use the alarm on the phone
Create sustainable reasons for oversleeping, first of all if you're up late (00, 01 >) and / or sleep during the day (making it harder to fall asleep during the night) - perhaps even creating a non-sleep event?

**Comment by StudioErrilhl** [comment]
Alarm clock was added

**Comment by StudioErrilhl** [comment]
Postponed till 0.27 (the alarm clock still works, ofc, but the embellishment for the reasons are currently not done)

**Comment by StudioErrilhl** [comment]
Closing this for now
